// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/restaurant-saas/Checkout.tsx": () => import("../components/mockups/restaurant-saas/Checkout.tsx"),
  "./components/mockups/restaurant-saas/Dashboard.tsx": () => import("../components/mockups/restaurant-saas/Dashboard.tsx"),
  "./components/mockups/restaurant-saas/LandingPage.tsx": () => import("../components/mockups/restaurant-saas/LandingPage.tsx"),
  "./components/mockups/restaurant-saas/Storefront.tsx": () => import("../components/mockups/restaurant-saas/Storefront.tsx"),
  "./components/mockups/restaurant-saas/SuperAdmin.tsx": () => import("../components/mockups/restaurant-saas/SuperAdmin.tsx")
};
